[settings]
auto_install = true
not_found_auto_install = true

[tools]
eza = "0.23.3"
fd = "10.3.0"
pre-commit = "4.3.0"
prettier = "3.6.2"
rg = "14.1.1"
shellcheck = "0.11.0"

# Linting tasks - check code quality (read-only)
[tasks.lint]
description = "Run all linting checks"
depends = ["lint:shellcheck", "lint:prettier"]

[tasks."lint:shellcheck"]
description = "Run shellcheck on shell scripts"
run = "shellcheck scripts/*.sh"
tools = { "shellcheck" = "0.11.0" }

[tasks."lint:prettier"]
description = "Check code formatting with prettier"
run = "prettier --check ."
tools = { "prettier" = "3.6.2" }

# Fix tasks - automatically fix issues where possible
[tasks.fix]
description = "Auto-fix all fixable issues"
depends = ["fix:prettier"]

[tasks."fix:prettier"]
description = "Auto-fix code formatting with prettier"
run = "prettier --write ."
tools = { "prettier" = "3.6.2" }

# Pre-commit workflow tasks - git hook management
[tasks."pre-commit"]
description = "Run all pre-commit hooks"
run = "pre-commit run --all-files"
tools = { "pre-commit" = "4.3.0" }

[tasks."pre-commit:install"]
description = "Install pre-commit hooks"
run = "pre-commit install"
tools = { "pre-commit" = "4.3.0" }
